spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  data:
    jpa:
      repositories:
        enabled: false

server:
  port: 8080

app:
  upload-dir: uploads
  jwt:
    secret: cGVyc29uYWxfc2l0ZV9kZW1vX3NlY3JldF9wZXJzb25hbF9zaXRlXzEyMw==
    expire-ms: 86400000
